# Generated by Django 4.0.2 on 2022-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
