# Generated by Django 4.0.2 on 2022-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answers_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='assumtion',
            name='assumtion_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assumtion',
            name='assumtion_link',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
