# Generated by Django 4.0.2 on 2022-06-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_assumtion_assumtion_index_assumtion_assumtion_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='assumtion_to_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumtion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assumtion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
