# Generated by Django 4.0.2 on 2022-06-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_answers_correct_assumtion_to_ans_assumtion_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_to_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumtion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assumtion_to_ans')),
            ],
        ),
        migrations.CreateModel(
            name='answer_to_ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question_to_ans')),
            ],
        ),
    ]
