# Generated by Django 4.0.2 on 2022-06-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_question_to_ans_answer_to_ans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='assumtion',
            new_name='assessment',
        ),
        migrations.RenameField(
            model_name='assumtion_to_ans',
            old_name='assumtion_id',
            new_name='assessment_id',
        ),
        migrations.RenameField(
            model_name='assumtion_to_ans',
            old_name='assumtion_result',
            new_name='assessment_result',
        ),
        migrations.RenameField(
            model_name='question_to_ans',
            old_name='assumtion_id',
            new_name='assessment_id',
        ),
    ]
