# Generated by Django 4.0.2 on 2022-06-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_assumtion_assessment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assumtion_index',
            new_name='assessment_index',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assumtion_link',
            new_name='assessment_link',
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='assumtion_name',
            new_name='assessment_name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='assumtion_id',
            new_name='assessment_id',
        ),
    ]
