# Generated by Django 4.0.2 on 2022-06-25 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_activation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='activation',
            new_name='activation_form',
        ),
    ]
